### ISSUE TITLE
Coveralls fails due to malformed src directory

### ISSUE THREAD

**Issue by dav3r** [cisagov/pca-report-library#8]
# 🐛 Summary #

`coveralls` is failing- we (@mcdonnnj and @dav3r) believe this is because the `src/` directory in this repo does not conform to a [normal Python library](https://packaging.python.org/tutorials/packaging-projects/).

To fix this issue, convert this repo from a descendant of [`skeleton-generic`](https://github.com/cisagov/skeleton-generic) to a descendant of [`skeleton-python-library`](https://github.com/cisagov/skeleton-python-library).

## To reproduce ##

1. `cd pca-report-library`
2. `COVERALLS_REPO_TOKEN=abcd1234 coveralls`

## Expected behavior ##

`coveralls` should run without any errors.

## Any helpful log output or screenshots ##

Paste the results here:

```console
Submitting coverage to coveralls.io...
Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/Users/dav3r/.pyenv/versions/pca-report-library/lib/python3.8/site-packages/coveralls/api.py", line 194, in wear
    response.raise_for_status()
  File "/Users/dav3r/.pyenv/versions/pca-report-library/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dav3r/.pyenv/versions/pca-report-library/lib/python3.8/site-packages/coveralls/cli.py", line 78, in main
    result = coverallz.wear()
  File "/Users/dav3r/.pyenv/versions/pca-report-library/lib/python3.8/site-packages/coveralls/api.py", line 197, in wear
    raise CoverallsException('Could not submit coverage: {}'.format(e))
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```

**Comment by dav3r** [comment]
This may not have been the problem that we thought.  After @ameliav and @nickviola got [a code branch](https://github.com/cisagov/pca-report-library/pull/9) in a state with a valid Python library structure, we still were seeing the same failure as above.

I was able to fix this problem by doing the following over on [coveralls.io](https://coveralls.io/github/cisagov/pca-report-library):
* Deleting the repo
* Re-adding the repo
* Re-syncing the repo with GitHub
* Regenerating a fresh `COVERALLS_REPO_TOKEN` and then updating the GitHub secret in this repo with the new token data

Finally, I re-ran the previously-failing PR tests and [saw them succeed](https://github.com/cisagov/pca-report-library/actions/runs/944097578).

My suspicion is that the root cause here has something to do with this repo's past history as a private repo.  I can't remember, but it may have also been previously owned by @bjb28 and not @cisagov.  I don't know if coveralls was able to properly handle the private/public and/or ownership changes of this repo.  

In any event, things appear to be working as expected now, so I am closing this issue.  Many thanks to @ameliav and @nickviola for their efforts thus far in updating this repo to our current standards!
